---
plugins:
  - flowtype
  - jest
  - babel

env:
  node: true
  jest/globals: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb'
  - 'prettier'
  - 'prettier/react'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'


rules:
  no-console: 0
